name: bluebeard-gnome-framework
description: A BlueBuild customized Fedora Atomic Desktop
base-image: ghcr.io/ublue-os/silverblue-framework
image-version: 39 # latest is also supported if you want new updates ASAP

modules:
  - from-file: common/silverblue-packages.yml
  - from-file: common/common-packages.yml
  - from-file: common/remove-firefox.yml
  - from-file: common/common-files.yml
  - type: signing
  - type: yafti

