type: rpm-ostree
repos:
install:
  - ansible
  - ansible-collection-community-general
  - ansible-collection-containers-podman
  - ansible-core-doc
  - difftastic
  - fd-find
  - foot
  - ripgrep
  - syncthing
  - strace
  - vim-X11
  - wl-clipboard

